### ISSUE TITLE
V1.35 - Sardania

### ISSUE THREAD

**Issue by pikachu1992** [edoaxyz/vtlog-map#3]
you will go to work on this?

**Comment by edoaxyz** [comment]
Sure but at this moment I'm busy with personal stuff and it won't be updated until the half of July

**Comment by pikachu1992** [comment]
still waitting for you

Edoardo Grassi <notifications@github.com> escreveu no dia terça, 25/06/2019
à(s) 10:33:

**Comment by edoaxyz** [comment]
Fixed with the latest commit 1fc0097d9ba6df56673dc29487e6fa771e39e2b6
